### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Hackndo** [Hackndo/sprayhound#1]
Add these features

- [ ] Add RPC and Kerberos authentication
- [ ] Add information about
    - [ ] Lockout
    - [ ] Password Expired
- [ ] Keep track of what password was tried on which account and make it run continuously
- [ ] Check all GPO because password policy can be defined elsewhere

**Comment by Elan0r** [comment]
Ola,
possible addition to the ideas could be: to add the "found" Password to BH, as used in [crackhound ](https://github.com/trustedsec/CrackHound) some self defined field like plaintextpassword. 
my python is not good enough to see how the --password parameter is handed over inside. 
the neo4j query just needs a `SET u.plaintextpassword="{1}"` or sth alike.

**Comment by Hackndo** [comment]
Hey there, I'm not working on this project anymore. I've created a new tool that, in my opinion, is way better, and checks almost all the ticks in this issue:

https://github.com/login-securite/conpass

- [ ] Add RPC and Kerberos authentication
- [x] Add information about
    - [x] Lockout
    - [ ] Password Expired
- [x] Keep track of what password was tried on which account and make it run continuously
- [x] Check all GPO because password policy can be defined elsewhere
